config/routes.rb
Rails.application.routes.draw do

  root 'users#home'

  resources :photos, only: [:create, :show] do
    resources :comments, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]

  end

  resources :journeys, except: [:index] do
    resources :diary_entries do
      resources :favourites, only: [:create, :destroy]
      resources :tags, only: [:create, :destroy, :show]
      resources :comments, only: [:create, :destroy]
    end
    resources :favourites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]
    resources :comments, only: [:create, :destroy]
    member do
      get :gallery
    end
    resources :photos, only: [:show, :update]
  end

  resources :tags, only: [:index]

  resources :users do
    member do
      get :followings, :followers
    end
    resources :photos
    resources :journeys, only: [:index]
    resources :favourites, only: [:index]
  end

  resources :relationships, only: [:destroy, :create]
  resources :password_resets

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true

  has_many :owend_journeys, class_name: "Journey", foreign_key: "owner_id"
  has_many :photos, :as => :imageable
  has_many :favourites
  has_many :tags


  def as_json(options={})
    super(#:only => [:first_name,:last_name,:city,:state],
          :include => [
            :owend_journeys #=> {:only => [:title, :description, :start_date, :end_date, :feat_img]}
          ]
    )
  end

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(another_user)
    self.active_relationships.create(followed_id: another_user.id)
  end

  def unfollow(another_user)
    self.active_relationships.find_by(followed_id: another_user.id).destroy
  end

  def follow?(another_user)
    self.followings.include?(another_user)
  end

  def set_profile_img
    if self.photos.last
      self.profile_img = self.photos.last.picture.public_id
    else
      self.profile_img = "default-picture-profile-i14.jpg"
    end
    self.save
    #code
  end

  def find_recommended
    @recommendation = self.tags.where(body: "recommended")
    @reco_array = []
    @recommendation.each { |x| @reco_array << x.taggable}
    @reco_array
  end

  def latest_recommendation
    @tags = self.tags.where(body: "recommended").last(4)
    @tags.map!.each do |r|
        r = r.taggable
    end
    @tags
  end

  def count_places
    diaryArray = []
    self.owend_journeys.each do |x|
      diaryArray.concat(x.diary_entries)
    end

    diaryLocation = []
    diaryArray.each do |d|
      diaryLocation << d.location
    end
    diaryArray.uniq!
    places_sum = diaryArray.count
    places_sum

  end

  def count_diaries
    diaryArray = []
    self.owend_journeys.each do |x|
      diaryArray.concat(x.diary_entries)
    end
    diaryArray.count
  end

  def last_diaries
    diaryArray = []
    self.owend_journeys.each do |x|
      diaryArray.concat(x.diary_entries)
    end
    diaryArray.sort! {|x,y| x.created_at <=> y.created_at }
    diaryArray.last(4)
  end

  def full_gallery
    full_gallery = []
    self.owend_journeys.each do |j|
      full_gallery.concat(j.photo_gallery)
    end
    full_gallery
  end

  def news_feed
    following_diary_entries = []
    self.followings.each do |following|
      following.owend_journeys.each do |journey|
        following_diary_entries.concat(journey.diary_entries)
      end
    following_diary_entries.last(5)
    end


    following_diary_entries.sort!{ |x,y| y[:updated_at] <=> x[:updated_at] }
    following_diary_entries.first(4)
  end


  def count_photos
    photosArray = []
    self.owend_journeys.each { |j| photosArray.concat(j.photo_gallery) }
    photosArray.count
  end

  def count_days
    days = 0

    self.owend_journeys.each do |j|
      if j.start_date != nil
      each_days = ((j.end_date - j.start_date) / 1.day).ceil
      days += each_days
      end
    end
    days
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "profile", except: [:index, :home, :new, :edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :followings, :followers]
  before_action :require_login, only: [:edit, :update, :destroy, :following, :followers]


  def index
    @users = User.all
    if params[:search]
      @search_results = DiaryEntry.where("lower(title) LIKE ?", "%#{params[:search].downcase}%")
      @search_results = @search_results.concat(Journey.where("lower(title) LIKE ?", "%#{params[:search].downcase}%"))
      @search_results.sort_by! {|result| result.created_at }
      @search_results.reverse!

      respond_to do |format|
        format.html
        format.js
      end
    else
      if current_user && current_user.email == "1@1.com"
        render :index
      else
        render file: "#{Rails.root}/public/404.html", layout: false, status: 404
      end
    end
  end


  def show
    respond_to do |format|
      format.html
      format.json
    end
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.set_profile_img
        auto_login(@user)
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :home, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.set_profile_img
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def followings
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @users = @user.followers
    render 'show_follow'
  end

  def home
    @search_results = []

    if params[:search]

      @search_results = DiaryEntry.near(params[:search], 50, unit: :km)
    elsif params[:latitude] && params[:longitude]
      @search_results = DiaryEntry.near([params[:latitude], params[:longitude]], 50, unit: :km)
    else
      @search_results = []
    end


    @diary_entry = DiaryEntry.last
    #
    # current_user.followers.each do |f|
    #   f.journeys.each do |j|
    #     j.diary_entries.last
    #   end

    # end

  end


  private


    def set_user
      @user = User.find(params[:id])
    end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :about)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def filter_string(content)
    raw_content = raw content
    output_content = raw_content[/\A"(.*)"\z/m,1]
    output_content
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "FOLLOW", class: "follow-button profile-button" %>
  <div class ="relationship-button-border button-border">FOLLOW</div>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.followings.include?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
    
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <%= f.email_field :email, :placeholder => "Enter Your Email", class:"login-input"  %>


    <%= f.text_field :name, :placeholder => "Name", class:"login-input"  %>


   <%= f.password_field :password, :placeholder => "Password", class:"login-input"  %>

     <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", class:"login-input"  %>


    <% if @user.name != nil %>
    <%= f.text_area :about, :placeholder => "Say something about yourself.", class:"login-input"  %>


    <%= f.submit "Edit", class: "btn_sign_up", :"data-no-turbolink" => true %>
    <% else %>
    <%= f.submit "Sign Up", class: "btn_sign_up", :"data-no-turbolink" => true%>
    <% end %>

<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  [&nbsp;&nbsp;
  <p>
    <%= link_to followings_user_path(@user), id: "following", :"data-no-turbolink" => true do %>

        followings <%= @user.followings.count %>

    <% end %>
  </p>

  <p>|&nbsp;&nbsp;&nbsp;
  <%= link_to followers_user_path(@user), id: "followers", :"data-no-turbolink" => true do %>

      followers <%= @user.followers.count %>

  <% end %>
  </p>
  ]

</div>

<div class="follow-button-container">
  <% if current_user %>
      <%= render 'follow_form' %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "UNFOLLOW", class: "follow-button profile-button" %>
  <div class ="relationship-button-border button-border">UNFOLLOW</div>
<% end %>

app/views/users/edit.html.erb
<!--
<%= link_to 'Show public profile', user_path(@user) %> |
<%= link_to 'Back', users_path %> -->
<div class="new-journey-wrapper">

  <div class="logo">
    <%= link_to root_url do%>
    <%= image_tag ("logo-blue.png")  %>
    <% end %>
  </div>

  <ul class="navigation">
    <li>
      <%= link_to current_user, :"data-no-turbolink" => true do %>
      <span>
      <%=  image_tag "MenuBar-icon-profile.png"  %>
      </span>
      <div class="menu-out">
        <%= image_tag "MenuBar-icon-profile-hover.png"%>
        <p>My Profile</p>
      </div>
    <% end %>
  </li>

    <li>
      <%= link_to user_journeys_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-Journey.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-Journey-hover.png"%>
          <p>My Journey</p>
        </div>
      <% end %>
    </li>

    <li>
      <%= link_to user_photos_path(current_user), :"data-no-turbolink" => true do %>
      <span>
      <%=  image_tag "MenuBar-icon-PhotoGallery.png"  %>
      </span>
      <div class="menu-out">
        <%= image_tag "MenuBar-icon-PhotoGallery-hover.png"%>
        <p>Gallery</p>
      </div>
      <% end %>
    </li>

    <li>
      <%= link_to new_journey_path, :"data-no-turbolink" => true do  %>
      <span>
      <%=  image_tag "MenuBar-icon-timeline.png"  %>
      </span>
      <div class="menu-out">
        <%= image_tag "MenuBar-icon-timeline-hover.png"%>
        <p>New Journey</p>
      </div>
      <% end %>
  </li>

    <li>
      <%= link_to user_favourites_path(current_user), :"data-no-turbolink" => true do %>
      <span>
      <%=  image_tag "MenuBar-icon-favorites.png"  %>
      </span>
      <div class="menu-out">
        <%= image_tag "MenuBar-icon-favorites-hover.png"%>
        <p>Favourites</p>
      </div>
      <% end %>
  </li>
    <!-- <li><a href="#contact">
      <img src="./images/contact.png" />
    </a></li> -->
  </ul>

<div class="edit-page-wrapper">
  <h1 class="edit-page-title">Edit My Profile</h1>
  <div class="modal">
    <label for="modal-1">
      <div class="modal-trigger">Set Profile Image</div>
    </label>
    <input class="modal-state" id="modal-1" type="checkbox" />
    <div class="modal-fade-screen">
      <div class="modal-inner">
        <div class="modal-close" for="modal-1"></div>
        <h1>Click to Add</h1>
        <div class="photo-form">
          <%= form_for Photo.new, html: { multipart: true, id: "my-awesome-dropzone", class: "dropzone"} do |t| %>
          <div class="dropzone-previews"></div>
          <br>
          <%= t.hidden_field :imageable_id, :value => @user.id %>
           <%= t.hidden_field :imageable_type, :value => @user.class %>
          <% end  %>
        </div>

      </div>
    </div>
  </div>
  <%= render 'form' %>

</div>
</div>

app/views/users/home.js.erb
$(".search_results").html(' <%= j(render 'tags/search_tag') %>')
// search results by location

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <!-- <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <!-- <td><%= user.crypted_password %></td> -->
        <!-- <td><%= user.salt %></td> -->
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/index.js.erb
$(".search_results").html(' <%= j(render 'tags/search_tag') %>')
// search results by name

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<style>
      html, body {
        height:100%;
        width:100%;
        padding: 0px;
        margin: 0px;
        background-color: white;
      }
</style>

<div class="profile-wrapper">
  <section id="page-content">
  <div class="empty-div"><p></p></div>
  <aside>
    <div class="about">
      <%= image_tag ("profile-SectionTitiles-about.png") %>
      <% if @user.about != nil %>
        <p><%= @user.about %></p>
      <% else %>
        <% if current_user == @user %>
          <p><%= link_to "Add your about statement.",  edit_user_path(@user) %></p>
        <% end %>
      <% end %>
    </div>

      <div class="grid-alligned-items">
        <a class="grid-alligned-item">
          <% if @user.full_gallery.length > 0 %>
            <%= cl_image_tag(@user.full_gallery.sample.picture.full_public_id, :format => "jpg", :width => 232, :height => 182,
            :crop => :fill) %>
            <% end %>
        </a>
        <a class="grid-alligned-item grid-alligned-item-big grid-alligned-item-image">
            <% if @user.full_gallery.length > 0  %>
              <%= cl_image_tag(@user.full_gallery.sample.picture.full_public_id, :format => "jpg", :width => 464, :height => 182,
               :crop => :fill) %>
            <% end %>
        </a>
        <a class="grid-alligned-item grid-alligned-item-big">
          <% if @user.full_gallery.length > 0 %>
            <%= cl_image_tag(@user.full_gallery.sample.picture.full_public_id, :format => "jpg", :width => 464, :height => 182,
            :crop => :fill) %>
          <% end %>
        </a>
        <a class="grid-alligned-item">
          <% if @user.full_gallery.length > 0 %>
            <%= cl_image_tag(@user.full_gallery.sample.picture.full_public_id, :format => "jpg", :width => 232, :height => 182,
            :crop => :lfill) %>
          <% end %>
        </a>
        <a class="grid-alligned-item">
          <% if @user.full_gallery.length > 0 %>
          <%= cl_image_tag(@user.full_gallery.sample.picture.full_public_id, :format => "jpg", :width => 232, :height => 182,
           :crop => :crop) %>
           <% end %>
        </a>
        <a class="grid-alligned-item">
          <% if @user.full_gallery.length > 0 %>
            <%= cl_image_tag(@user.full_gallery.sample.picture.full_public_id, :format => "jpg", :width => 232, :height => 182,
            :crop => :crop) %>
           <% end %>
        </a>
        <a class="grid-alligned-item">
          <% if @user.full_gallery.length > 0  %>
            <%= cl_image_tag(@user.full_gallery.sample.picture.full_public_id, :format => "jpg", :width => 232, :height => 182,
             :crop => :lfill) %>
          <% end %>
        </a>

      </div>

      <div class="photo-gallery-button-container">
        <a class="profile-button" href="<%= user_photos_path(@user) %>">VIEW ALL</a>
        <div class = "button-border" >VIEW ALL</div>
      </div>

      <div class="recomms">
        <%= image_tag ("profile-SectionTitiles-recommendations.png") %>

        <hr id="middle-vertical-line">
        <% if @user.latest_recommendation.first %>
          <% @user.latest_recommendation.first(4).each do |r| %>
          <div class="recomm">
            <% if r.class == Journey %>
            <%= link_to r do%>
            <h4 class="recomm-name"><%= r.title %></h4>
            <hr class="recomm-underline">
            <div class="recomm-text-editor"><%= r.description %></div>
              <% end %>
            <% else %>
            <%= link_to  journey_diary_entry_path(r.journey, r) do%>
            <h4 class="recomm-name"><%= r.title %></h4>
            <hr class="recomm-underline">
            <div class="recomm-text-editor"><%= filter_string(r.content) %></div>
              <% end %>
            <% end %>
          </div>
          <% end %>
        <% else %>
          <div class="recomm">
            <h4 class="recomm-name">Recommendation 1</h4>
            <hr class="recomm-underline">

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
          </div>


        <div class="recomm">
          <h4 class="recomm-name">Recommendation 2</h4>
          <hr class="recomm-underline">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
        </div>

        <div class="recomm">
          <h4 class="recomm-name">Recommendtion 3</h4>
          <hr class="recomm-underline">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
        </div>

        <div class="recomm">
          <h4 class="recomm-name">Recommendation 4</h4>
          <hr class="recomm-underline">

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
        </div>
    <% end %>
    </div>

        <!-- <div class="recommendation-body">
          <% @user.find_recommended.each do |r| %>
            <h3>  <%= r.title %> </h3>
              <% if r.class == Journey %>
              <strong>  <%= r.owner.email %> </strong>
                <%= r.description %>
              <% else %>
              <strong>  <%= r.journey.owner.email%><strong>
                <%= r.content %>
            <% end %>
          <% end %>
        </div> -->
  </aside>
  <article>
    <div class="overall">
      <%= image_tag ('profile-SectionTitiles-overall.png') %>
      <div class="couter">
        <div class="counter1">
          Traveled <strong><%= @user.count_places %></strong> Places
        </div>
        <div class="counter1">
          Wrote <strong><%= @user.count_diaries %></strong> Diaries
        </div>
        <div class="counter1">
          Captured <strong><%= @user.count_photos %></strong> Moments
        </div>
        <div class="counter2">
          Stayed <strong><%= @user.count_days %></strong>Days On The Road
        </div>
      </div>
    </div>

    <div class="user-Timeline-section">
      <div class="userTimeline-image1">
        <%= image_tag ('profile-SectionTitiles-timeline.png') %>
      </div>
      <div class="userTimeline-image2">
        <%= image_tag ('profile-timeline-bg.jpg') %>
      </div>
      <div class="timeline-button-container">
        <button class="profile-button timeline-button-border">VIEW TIMELINE</button>
        <div class = "button-border" >VIEW TIMELINE</div>
      </div>
      <div class="map-button-container">
        <button class="profile-button">VIEW MAP</button>
        <div class = "button-border" >VIEW MAP</div>
      </div>
    </div>


    <div class="activity-stream">
      <div class="stream-picture">
        <%= image_tag("profile-activitystream.png") %>
      </div>
      <div class="activity-stream-img">
      <%= image_tag ('profile-SectionTitiles-activities.png') %>
      </div>
      <% if @user.last_diaries %>
        <% @user.last_diaries.each do |d|%>
        <div class="user-diary-activity">
          <div class="activity-title">
            <%= link_to journey_diary_entry_path(d.journey, d), :"data-no-turbolink" => true do%>
            <h2><%= d.title %></h2>
            <% end %>
            <h3><%= truncate(d.location, length: 25) %> | <%=d.show_time(d.date) %></h3>
            <div class="stream-content"><%= filter_string(d.content) %></div>

          <div class="activity-tags">
          <%   d.tags.last(3).each do |t| %>
            <% if t.body != "recommended" %>
              <span class="tag-span"><%= t.body %></span>
              <% end %>
          <% end %>
              <!-- <span>Tag</span>
              <span>Tag</span> -->


          </div>
        </div>
        <% end %>
      <% end %>

    <div class="activity-button-container">
      <a class="profile-button" href="<%= user_journeys_path(@user) %>">VIEW ALL</a>
      <div class = "button-border" >VIEW ALL</div>
    </div>


  </article>
</section>
</div>

<div class="footer">
  <div class="footer-image">
    <%= image_tag "profile-graphic_MountainLowPoy.png" %>
  </div>
</div>

  <div class="hidden-map">
  <a id="demo01" href="#animatedModal">My Path</a>

  <div id="animatedModal">
    <div class="close-animatedModal">
      <Strong>Go Back!</Strong>
    </div>

    <div class="modal-content">
      <div id="path_map"><%= link_to 'My Path',  user_journeys_path(@user) %></div>

    </div>
  </div>
  </div>

app/views/users/show_follow.html.erb
<!-- <div class="follow-container"> -->
<!-- </div> -->

<div class="follow-page-wrapper">
<% if @users.any? %>
  <% @users.each do |user| %>
  <div class="follow-container">
  <div class="follow-user-profileimg">
    <%= cl_image_tag(user.profile_img, :width=>75, :height=>75, :crop=>:thumb) %>
  </div>
  <div class="follow-user-info">
    <h1>  <%= link_to user.name, user %></h1>
    <p> Following : <%= link_to user.followings.count, followings_user_path(user) %> | Follower :<%= link_to user.followers.count, followers_user_path(user) %></p>
    <% if user.owend_journeys.last %>
      <span>Last Location:     <%= user.owend_journeys.last.location %></span>
    <% end %>
    <p class="follow-page-about-content"><%= user.about %></p>
    <p class="follow-user-detail"></p>
  </div>
  <div class="follow-page-button">
  </div>
  </div>
  <% end %>
<% end %>
</div>
<!--
<div class="comment">
  <div class="comment-image">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2.png" alt="Logo image">
  </div>
  <div class="comment-content">
    <h1>Another One</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, aspernatur, quia modi minima debitis tempora ducimus quam vero impedit alias earum nemo error tenetur sed.</p>
    <p class="comment-detail">Date or details about this post</p>
  </div>
</div> -->