config/routes.rb
Rails.application.routes.draw do

  root 'users#home'

  resources :photos, only: [:create, :show] do
    resources :comments, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]

  end

  resources :journeys, except: [:index] do
    resources :diary_entries do
      resources :favourites, only: [:create, :destroy]
      resources :tags, only: [:create, :destroy, :show]
      resources :comments, only: [:create, :destroy]
    end
    resources :favourites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]
    resources :comments, only: [:create, :destroy]
    member do
      get :gallery
    end
    resources :photos, only: [:show, :update]
  end

  resources :tags, only: [:index]

  resources :users do
    member do
      get :followings, :followers
    end
    resources :photos
    resources :journeys, only: [:index]
    resources :favourites, only: [:index]
  end

  resources :relationships, only: [:destroy, :create]
  resources :password_resets

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/diary_entry.rb
class DiaryEntry < ActiveRecord::Base
  belongs_to :journey
  has_many :photos, :as => :imageable
  has_many :favourites, :as => :favourable
  has_many :tags, :as => :taggable

  has_many :comments, :as => :commentable
  validates :title, :location, :date, :recommendation, presence: true

  # attr_accessor :location, :longitude, :latitude
  geocoded_by :location
  after_validation :geocode

  def show_time(created_at)
    created_at.strftime('%b %e %Y %H :%M :%S %p')
  end

end

app/controllers/diary_entries_controller.rb
class DiaryEntriesController < ApplicationController
  # layout "profile", only: [:index]
  before_action :find_journey

  def new
    # @journey = Journey.find(params[:journey_id])
    @diary_entry = @journey.diary_entries.build
  end


  def create
    if diary_entry_params[:title] == DiaryEntry.last.title
      render nothing: true
    else

      if params.has_key?("content")
        @diary_entry = DiaryEntry.last
        @diary_entry.update_attributes({:content => params[:content]})
        @diary_entry.save
        render nothing: true, status: 200
      else
          if diary_entry_params[:imageable_type]
            @diary_entry = current_user.last_diaries.last
            @photo = @diary_entry.photos.build(diary_entry_params)
            @photo.picture = params[:file]
            @photo.save
            render nothing: true, status: 200
          else
            @diary_entry = @journey.diary_entries.build(diary_entry_params)

            if @diary_entry.save
              respond_to do |format|
                format.html {redirect_to journey_diary_entries_path, notice: "Diary successfully created!"}
                format.json { render nothing: true, status: 200}
              end

            else
            render :new
            end
        end
      end
    end
  end

  def index
    @user = @journey.owner
    # @journey = Journey.find(params[:journey_id])
    @diary_entries = @journey.diary_entries

    respond_to do |format|
      format.html
      format.json { render json: @diary_entries }
    end
  end

  def show
    @diary_entry = @journey.diary_entries.find(params[:id])
    @user = @journey.owner
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.json { render json: {latitude: @diary_entry.latitude, longitude: @diary_entry.longitude} }
    end
  end

  def edit
    @diary_entry = DiaryEntry.find(params[:id])
  end

  def update
    if params.has_key?("content")
      @diary_entry = DiaryEntry.find(params[:id])
      @diary_entry.update_attributes({:content => params[:content]})
      @diary_entry.save
      render nothing: true, status: 200
    else
      @diary_entry = DiaryEntry.find(params[:id])

      if @diary_entry.update_attributes(diary_entry_params)
        respond_to do |format|
          format.html {redirect_to journey_diary_entry_path(@diary_entry.journey, @diary_entry), notice: "Diary successfully created!"}
          format.json { render nothing: true, status: 200}
        end
      else
        render :edit
      end
    end

  end

  def destroy
    if current_user.id == @journey.owner_id
      @diary_entry = @journey.diary_entries.find(params[:id])
      @diary_entry.destroy
    end
    redirect_to journey_diary_entries_path(@journey.id)
  end

  def find_journey
    @journey = Journey.find(params[:journey_id])

  end

  private
  def diary_entry_params
    params.require(:diary_entry)
          .permit(:title, :location, :date, :content, :recommendation, :latitude, :longitude, :imageable_id, :imageable_type)
  end
end

app/helpers/diary_entries_helper.rb
module DiaryEntriesHelper
end

app/views/diary_entries/_diary_entry.html.erb
<div class="diary_entry_block">
  <%= link_to journey_diary_entry_path(diary_entry.journey, diary_entry), :"data-no-turbolink" => true do %>
  <div>
    <%= cl_image_tag (diary_entry.photos.first ? "#{diary_entry.photos.first.picture.url}" : ""),  width: "200", height: "200", crop: "lfill", class: "diary_img_preview" %>
  </div>
  <div class="diary_text_preview">
    <span class="diary-title">
      <%= truncate(diary_entry.title, length: 13) %>
    </span>
    <span>
      <%= truncate(diary_entry.location, length: 15) %> |
      <%= "Day #{((diary_entry.date - diary_entry.journey.start_date) / 1.day).ceil + 1}" %>
    </span>
  </div>
  <% end %>
</div>

app/views/diary_entries/edit.html.erb
<div class="new-journey-wrapper">


<div class="logo">
  <%= link_to root_url do%>
  <%= image_tag ("logo-blue.png")  %>
  <% end %>
</div>

<ul class="navigation">
  <li>
    <%= link_to current_user, :"data-no-turbolink" => true do %>
    <span>
    <%=  image_tag "MenuBar-icon-profile.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-profile-hover.png"%>
      <p>My Profile</p>
    </div>
  <% end %>
</li>

  <li>
    <%= link_to user_journeys_path(current_user), :"data-no-turbolink" => true do %>
      <span>
      <%=  image_tag "MenuBar-icon-Journey.png"  %>
      </span>
      <div class="menu-out">
        <%= image_tag "MenuBar-icon-Journey-hover.png"%>
        <p>My Journey</p>
      </div>
    <% end %>
  </li>

  <li>
    <%= link_to user_photos_path(current_user), :"data-no-turbolink" => true do %>
    <span>
    <%=  image_tag "MenuBar-icon-PhotoGallery.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-PhotoGallery-hover.png"%>
      <p>Gallery</p>
    </div>
    <% end %>
  </li>

  <li>
    <%= link_to new_journey_path, :"data-no-turbolink" => true do  %>
    <span>
    <%=  image_tag "MenuBar-icon-timeline.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-timeline-hover.png"%>
      <p>New Journey</p>
    </div>
    <% end %>
</li>

  <li>
    <%= link_to user_favourites_path(current_user), :"data-no-turbolink" => true do %>
    <span>
    <%=  image_tag "MenuBar-icon-favorites.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-favorites-hover.png"%>
      <p>Favourites</p>
    </div>
    <% end %>
</li>
  <!-- <li><a href="#contact">
    <img src="./images/contact.png" />
  </a></li> -->
</ul>


<% if current_user.id == @diary_entry.journey.owner_id %>


<h1 class="new-diary">Edit Diary</h1>
<!-- multistep form -->
<div id="msform">
  <div class="diary-form">
	<!-- progressbar -->
	<ul id="progressbar-diary">
		<li class="active">Basic Info</li>
		<li>About this Diary </li>
		<li>Photo Collection</li>
	</ul>
	<!-- fieldsets -->
	<fieldset>
		<h2 class="fs-title">Create your Diary</h2>
		<h3 class="fs-subtitle">Step One</h3>
	  <%= render 'form' %>
		<input type="button" name="next" class="next action-button" value="Next" id="first_diary" />
	</fieldset>
	<fieldset class="fieldset1">
		<h2 class="fs-title">Desciption</h2>
		<h3 class="fs-subtitle">Say something for your diary</h3>

		<!-- <input type="text" name="twitter" placeholder="Twitter" />
		<input type="text" name="facebook" placeholder="Facebook" />
		<input type="text" name="gplus" placeholder="Google Plus" /> -->

    <div class="text-editor">
      <div class="newPost">
        <!-- <h3>Write Your Diary</h3> -->
        <!-- <input type="text" placeholder="Enter title here"> -->
        <div class="toolbar">
          <button type="button" data-func="bold"><i class="fa fa-bold"></i></button>
          <button type="button" data-func="italic"><i class="fa fa-italic"></i></button>
          <button type="button" data-func="underline"><i class="fa fa-underline"></i></button>
          <button type="button" data-func="justifyleft"><i class="fa fa-align-left"></i></button>
          <button type="button" data-func="justifycenter"><i class="fa fa-align-center"></i></button>
          <button type="button" data-func="justifyright"><i class="fa fa-align-right"></i></button>
          <button type="button" data-func="insertunorderedlist"><i class="fa fa-list-ul"></i></button>
          <button type="button" data-func="insertorderedlist"><i class="fa fa-list-ol"></i></button>
          <div class="customSelect">
            <select data-func="fontname">
              <optgroup label="Serif Fonts">
                <option value="Bree Serif">Bree Serif</option>
                <option value="Georgia">Georgia</option>
                <option value="Palatino Linotype">Palatino Linotype</option>
                <option value="Times New Roman">Times New Roman</option>
              </optgroup>
              <optgroup label="Sans Serif Fonts">
                <option value="Arial">Arial</option>
                <option value="Arial Black">Arial Black</option>
                <option value="Asap" selected>Asap</option>
                <option value="Comic Sans MS">Comic Sans MS</option>
                <option value="Impact">Impact</option>
                <option value="Lucida Sans Unicode">Lucida Sans Unicode</option>
                <option value="Tahoma">Tahoma</option>
                <option value="Trebuchet MS">Trebuchet MS</option>
                <option value="Verdana">Verdana</option>
              </optgroup>
              <optgroup label="Monospace Fonts">
                <option value="Courier New">Courier New</option>
                <option value="Lucida Console">Lucida Console</option>
              </optgroup>
            </select>
          </div>
          <div class="customSelect">
            <select data-func="formatblock">
              <option value="h1">Heading 1</option>
              <option value="h2">Heading 2</option>
              <option value="h4">Subtitle</option>
              <option value="p" selected>Paragraph</option>
            </select>
          </div>
        </div>
        <div class="editor" contenteditable></div>
        <div class="buttons">
          <!--<button type="button">save draft</button>-->
          <button data-func="clear" type="button" >clear</button>
          <button data-func="save" type="button" style="visibility:hidden">save</button>
        </div>
      </div>
    </div>

		<input type="button" name="previous" class="previous action-button" value="Previous" />
		<input type="button" id="second_diary" name="next" class="next action-button" value="Next" />
	</fieldset>

	<fieldset id="diary-last-step">
		<h2 class="fs-title">Photos</h2>
		<h3 class="fs-subtitle">
      <p>Upload your photos here</p>
    </h3>
    <div class="photo-form" id="photo-last-step">
      <%= form_for Photo.new, html: { multipart: true, id: "my-awesome-dropzone", class: "dropzone"} do |t| %>



      <div class="dropzone-previews"></div>
      <br>
      <%= t.hidden_field :imageable_id, :value => @diary_entry.id %>
     <%= t.hidden_field :imageable_type, :value => @diary_entry.class %>
      <% end  %>
		<!-- <input type="text" name="fname" placeholder="First Name" />
		<input type="text" name="lname" placeholder="Last Name" />
		<input type="text" name="phone" placeholder="Phone" />
		<textarea name="address" placeholder="Address"></textarea> -->
    </div>
		<input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="submit" name="submit" class="submit action-button" value="Submit" id="final_diary" />
	</fieldset>
  </div>
</div>

<div class="h-link">
  <%= link_to "", journey_diary_entry_path(@journey, @diary_entry) %>
</div>
</div>




<% end %>

app/views/diary_entries/new.html.erb
<div class="new-journey-wrapper" id="new-diary-wrapper">


<div class="logo">
  <%= link_to root_url do%>
  <%= image_tag ("logo-blue.png")  %>
  <% end %>
</div>

<ul class="navigation">
  <li>
    <%= link_to current_user, :"data-no-turbolink" => true do %>
    <span>
    <%=  image_tag "MenuBar-icon-profile.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-profile-hover.png"%>
      <p>My Profile</p>
    </div>
  <% end %>
</li>

  <li>
    <%= link_to user_journeys_path(current_user), :"data-no-turbolink" => true do %>
      <span>
      <%=  image_tag "MenuBar-icon-Journey.png"  %>
      </span>
      <div class="menu-out">
        <%= image_tag "MenuBar-icon-Journey-hover.png"%>
        <p>My Journey</p>
      </div>
    <% end %>
  </li>

  <li>
    <%= link_to user_photos_path(current_user), :"data-no-turbolink" => true do %>
    <span>
    <%=  image_tag "MenuBar-icon-PhotoGallery.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-PhotoGallery-hover.png"%>
      <p>Gallery</p>
    </div>
    <% end %>
  </li>

  <li>
    <%= link_to new_journey_path, :"data-no-turbolink" => true do  %>
    <span>
    <%=  image_tag "MenuBar-icon-timeline.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-timeline-hover.png"%>
      <p>New Journey</p>
    </div>
    <% end %>
</li>

  <li>
    <%= link_to user_favourites_path(current_user), :"data-no-turbolink" => true do %>
    <span>
    <%=  image_tag "MenuBar-icon-favorites.png"  %>
    </span>
    <div class="menu-out">
      <%= image_tag "MenuBar-icon-favorites-hover.png"%>
      <p>Favourites</p>
    </div>
    <% end %>
</li>
  <!-- <li><a href="#contact">
    <img src="./images/contact.png" />
  </a></li> -->
</ul>


<% if current_user.id == @diary_entry.journey.owner_id %>


<h1 class="new-diary">New Diary</h1>
<!-- multistep form -->
<div id="msform">
  <div class="diary-form">
	<!-- progressbar -->
	<ul id="progressbar-diary">
		<li class="active">Basic Info</li>
		<li>About this Diary </li>
		<li>Photo Collection</li>
	</ul>
	<!-- fieldsets -->
	<fieldset>
		<h2 class="fs-title">Create your Diary</h2>
		<h3 class="fs-subtitle">Step One</h3>
	  <%= render 'form' %>
		<input type="button" name="next" class="next action-button" value="Next" id="first_diary" />
	</fieldset>
	<fieldset class="fieldset1">
		<h2 class="fs-title">Desciption</h2>
		<h3 class="fs-subtitle">Say something for your diary</h3>

		<!-- <input type="text" name="twitter" placeholder="Twitter" />
		<input type="text" name="facebook" placeholder="Facebook" />
		<input type="text" name="gplus" placeholder="Google Plus" /> -->

    <div class="text-editor">
      <div class="newPost">
        <!-- <h3>Write Your Diary</h3> -->
        <!-- <input type="text" placeholder="Enter title here"> -->
        <div class="toolbar">
          <button type="button" data-func="bold"><i class="fa fa-bold"></i></button>
          <button type="button" data-func="italic"><i class="fa fa-italic"></i></button>
          <button type="button" data-func="underline"><i class="fa fa-underline"></i></button>
          <button type="button" data-func="justifyleft"><i class="fa fa-align-left"></i></button>
          <button type="button" data-func="justifycenter"><i class="fa fa-align-center"></i></button>
          <button type="button" data-func="justifyright"><i class="fa fa-align-right"></i></button>
          <button type="button" data-func="insertunorderedlist"><i class="fa fa-list-ul"></i></button>
          <button type="button" data-func="insertorderedlist"><i class="fa fa-list-ol"></i></button>
          <div class="customSelect">
            <select data-func="fontname">
              <optgroup label="Serif Fonts">
                <option value="Bree Serif">Bree Serif</option>
                <option value="Georgia">Georgia</option>
                <option value="Palatino Linotype">Palatino Linotype</option>
                <option value="Times New Roman">Times New Roman</option>
              </optgroup>
              <optgroup label="Sans Serif Fonts">
                <option value="Arial">Arial</option>
                <option value="Arial Black">Arial Black</option>
                <option value="Asap" selected>Asap</option>
                <option value="Comic Sans MS">Comic Sans MS</option>
                <option value="Impact">Impact</option>
                <option value="Lucida Sans Unicode">Lucida Sans Unicode</option>
                <option value="Tahoma">Tahoma</option>
                <option value="Trebuchet MS">Trebuchet MS</option>
                <option value="Verdana">Verdana</option>
              </optgroup>
              <optgroup label="Monospace Fonts">
                <option value="Courier New">Courier New</option>
                <option value="Lucida Console">Lucida Console</option>
              </optgroup>
            </select>
          </div>
          <div class="customSelect">
            <select data-func="formatblock">
              <option value="h1">Heading 1</option>
              <option value="h2">Heading 2</option>
              <option value="h4">Subtitle</option>
              <option value="p" selected>Paragraph</option>
            </select>
          </div>
        </div>
        <div class="editor" contenteditable></div>
        <div class="buttons">
          <!--<button type="button">save draft</button>-->
          <button data-func="clear" type="button" >clear</button>
          <button data-func="save" type="button" style="visibility:hidden">save</button>
        </div>
      </div>
    </div>

		<input type="button" name="previous" class="previous action-button" value="Previous" />
		<input type="button" id="second_diary" name="next" class="next action-button" value="Next" />
	</fieldset>

	<fieldset id="diary-last-step">
		<h2 class="fs-title">Photos</h2>
		<h3 class="fs-subtitle">
      <p>Upload your photos here</p>
    </h3>
    <div class="photo-form" id="photo-last-step">
      <%= form_for [@journey, DiaryEntry.new], html: { multipart: true, id: "my-awesome-dropzone", class: "dropzone"} do |t| %>



      <div class="dropzone-previews"></div>
      <br>
      <%= t.hidden_field :imageable_id, :value => @diary_entry.id %>
     <%= t.hidden_field :imageable_type, :value => @diary_entry.class %>
      <% end  %>
		<!-- <input type="text" name="fname" placeholder="First Name" />
		<input type="text" name="lname" placeholder="Last Name" />
		<input type="text" name="phone" placeholder="Phone" />
		<textarea name="address" placeholder="Address"></textarea> -->
    </div>
		<input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="submit" name="submit" class="submit action-button" value="Submit" id="final_diary" />
	</fieldset>
  </div>
</div>

<div class="h-link">
  <%= link_to "", journey_path(@journey)%>
</div>

</div>



<% end %>

<script>
  $(document).ready(function () {

  $(".new_diary_entry").validate({
    debug: true,
    rules: {
    "diary_entry[title]": {required: true, minlength: 4},
    "diary_entry[location]": {required: true, minlength: 6},
    "diary_entry[date]": {required: true},
    "diary_entry[recommendation]": {required: true}
    // “user[password_confirmation]“: {required: true, equalTo: “#user_password”}
    }
  });


  // $(".existing-journey").validate({
  //   debug: true,
  //   rules: {
  //   "journey[description]": {required: true, minlength: 7}
  //
  //   // “user[password_confirmation]“: {required: true, equalTo: “#user_password”}
  //   }
  //   });

  });
</script>

app/views/diary_entries/show.html.erb
<!DOCTYPE html>
<body>

    <div class="back-img-diary">
      <div class="logo">
        <%= link_to root_url do%>
        <%= image_tag ("logo-blue.png")  %>
        <% end %>
      </div>

      <div class="hero-inner">
        <div class="hero-copy">
          <h1 class="diary-title"><%= @diary_entry.title %></h1>
            <h2 class="diary-author">Written by <%= link_to @user.name, @user %></h2>

        </div>
      </div>

    </div>

  <% if current_user %>
    <ul class="navigation">
      <li>
        <%= link_to current_user, :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-profile.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-profile-hover.png"%>
          <p>My Profile</p>
        </div>
      <% end %>
    </li>

      <li>
        <%= link_to user_journeys_path(@user), :"data-no-turbolink" => true do %>
          <span>
          <%=  image_tag "MenuBar-icon-Journey.png"  %>
          </span>
          <div class="menu-out">
            <%= image_tag "MenuBar-icon-Journey-hover.png"%>
            <p>My Journey</p>
          </div>
        <% end %>
      </li>

      <li>
        <%= link_to user_photos_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-PhotoGallery.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-PhotoGallery-hover.png"%>
          <p>Gallery</p>
        </div>
        <% end %>
      </li>

      <li>
        <%= link_to new_journey_path, :"data-no-turbolink" => true do  %>
        <span>
        <%=  image_tag "MenuBar-icon-timeline.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-timeline-hover.png"%>
          <p>New Journey</p>
        </div>
        <% end %>
    </li>

      <li>
        <%= link_to user_favourites_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-favorites.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-favorites-hover.png"%>
          <p>Favourites</p>
        </div>
        <% end %>
    </li>
      <!-- <li><a href="#contact">
        <img src="./images/contact.png" />
      </a></li> -->
    </ul>
  <% end %>


<div class="diary-wrapper">

  <div class="diary-picture-stat-section">
    <div class="journey-buttons-section">
      <% if current_user == @diary_entry.journey.owner %>
      <%= link_to "EDIT DIARY", edit_journey_diary_entry_path(@diary_entry.journey, @diary_entry), :"data-no-turbolink" => true, :"class" => "profile-button" %>
        <div class = "button-border" >EDIT DIARY</div>
      <% end %>
    </div>

    <div class="diary-picture diary_aside">
      <% if @diary_entry.photos.first %>
        <%= cl_image_tag(@diary_entry.photos.first.picture.url, :class => "diary_entry_img") %>
      <% else %>
      <%= cl_image_tag("img_placeholder.png", :class => "diary_entry_img") %>
      <% end %>
    </div>

    <div class="diary-stats diary_article">
      <div class="diary-stat">
        <%= image_tag ('Entries_icon_location.png') %>
        <h3 class="diary-stat-name">LOCATION</h3>
        <p class="diary-stat-content"><%= @diary_entry.location %></p>
      </div>
      <div class="diary-stat">
        <%= image_tag ('Entries_icon_time.png') %>
        <h3 class="diary-stat-name">DATE</h3>
        <p class="diary-stat-content"><%= @diary_entry.show_time(@diary_entry.date)%></p>
      </div>
      <div class="diary-stat">
        <%= image_tag ('Entries_icon_tag.png') %>
        <h3 class="diary-stat-name">TAGS</h3>
        <div class="activity-tags">
           <% @diary_entry.tags.each do |tag| %>
              <% if tag.body != "recommended" %>
              <div class="listing-tag">
                  <%= tag.body %>
              </div>
                <% end %>
          <% end %>

          <% if current_user == @diary_entry.journey.owner %>
            <span class="add-new-tag"><%= link_to "Add Tags" %></span>



          <div class="tag-form">
            <%= form_for [@diary_entry.journey, @diary_entry, Tag.new] do |t| %>

            <%= t.text_field :body, :placeholder => 'Descripe your diary' %>
            <%= t.hidden_field :taggable_id, :value => @diary_entry.id %>
            <%= t.hidden_field :taggable_type, :value => @diary_entry.class %>
            <%= t.hidden_field :user_id, :value => current_user.id %>
            <%= t.submit "Add" %>
            <% end  %>
          </div>
          <% end %>
        </div>

      </div>
      <div class="diary-stat">
        <%= image_tag ('Entries_icon_tips.png') %>
        <h3 class="diary-stat-name">TIPS</h3>
        <p class="diary-stat-content"><%= @diary_entry.recommendation %> </p>

      </div>
    </div>
  </div>

  <div class="diary-content-picture-section">
    <div class="diary-content diary_aside">
      <div class="diary-content-left"><%= filter_string(@diary_entry.content) %></div>
      <% if current_user && current_user != @diary_entry.journey.owner%>
      <div class="recommend diary-content">
        <% if @diary_entry.tags.where(user_id: current_user.id, body: "recommended").size > 0 %>
          <button class="recommend-alreday" type="button" name="button">Recommend</button>

        <% else %>
        <div class="recommend-form">
          <%= form_for [@diary_entry.journey, @diary_entry, Tag.new] do |t| %>
          <%= t.hidden_field :body, :value=> 'recommended' %>
          <%= t.hidden_field :taggable_id, :value => @diary_entry.id %>
          <%= t.hidden_field :taggable_type, :value => @diary_entry.class %>
          <%= t.hidden_field :user_id, :value => current_user.id %>
          <%= t.submit "Recommend" %>

          <% end  %>
        </div>
        <% end %>
      </div>
      <div class="favourite-diary">
        <% if @diary_entry.favourites.where(user_id: current_user.id).length > 0 %>
          <button class="f-already">
            <span class="fa fa-heart">
              </span>
          </button>
          <div class="favourite-form-already">
            <%= form_for [@diary_entry.journey, @diary_entry, @diary_entry.favourites.where(user_id: current_user.id)[0]], method: :delete do |f| %>
            <%= f.button :class => "submit-already" %>
            <% end %>
          </div>
        <% else %>
          <button class="no-f-yet">
            <span class="fa fa-heart">
              </span>
          </button>
          <div class="favourite-form">
            <%= form_for [@diary_entry.journey, @diary_entry, Favourite.new] do |f| %>
            <%= f.button :class => "f-submit" %>
            <% end %>
          </div>
        <% end %>
      </div>
      <% end %>


    </div>
    <div class="diary-picture diary_article">
      <% if @diary_entry.photos.second %>
        <%= cl_image_tag(@diary_entry.photos.second.picture.url, :class => "diary_entry_img diary_entry_img2") %>
      <% else %>
      <%= cl_image_tag("img_placeholder.png", :class => "diary_entry_img diary_entry_img2") %>
      <% end %>
    </div>

  </div>

  <div class="comment-form-list-section">
    <div class="diary-comment-form diary_aside">
      <%= image_tag ("Entries_SectionTitle_Comments.png") %>
      <% if current_user %>

        <%= form_for [@diary_entry.journey, @diary_entry, @comment], :html => {:class => "comment-form"} do |f| %>
        <%= render partial: 'comments/form', locals: { f: f, commentable: @diary_entry} %>
        <% end %>
      <% else %>
        <p>Please <%= link_to "log in", login_path %> to add a comment.</p>
      <% end %>
    </div>

    <div class="comment-list diary_article">
      <%= render partial: 'comments/list', locals: { commentable: @diary_entry }  %>

    </div>
  </div>

</div>

</body>