config/routes.rb
Rails.application.routes.draw do

  root 'users#home'

  resources :photos, only: [:create, :show] do
    resources :comments, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]

  end

  resources :journeys, except: [:index] do
    resources :diary_entries do
      resources :favourites, only: [:create, :destroy]
      resources :tags, only: [:create, :destroy, :show]
      resources :comments, only: [:create, :destroy]
    end
    resources :favourites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]
    resources :comments, only: [:create, :destroy]
    member do
      get :gallery
    end
    resources :photos, only: [:show, :update]
  end

  resources :tags, only: [:index]

  resources :users do
    member do
      get :followings, :followers
    end
    resources :photos
    resources :journeys, only: [:index]
    resources :favourites, only: [:index]
  end

  resources :relationships, only: [:destroy, :create]
  resources :password_resets

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/journey.rb
class Journey < ActiveRecord::Base

  belongs_to :owner, class_name: "User"
  has_many :diary_entries
  has_many :photos, :as => :imageable
  has_many :favourites, :as => :favourable
  has_many :tags, :as => :taggable
  has_many :comments, :as => :commentable
  # validates :title, :description, :location, presence: true

  validates :title, :location, :start_date, :end_date, presence: true

  def photo_gallery
    @photo_gallery = []
    @photo_gallery.concat(self.photos)
      self.diary_entries.each do |y|
         @photo_gallery.concat(y.photos)
       end
    @photo_gallery
  end



  def set_as_feat_img(photo)
    self.feat_img = photo.picture.public_id
    self.save
  end

  def set_feat_img
    if self.feat_img == "img_placeholder.png"
      if self.photo_gallery.last
        self.feat_img = self.photo_gallery.last.picture.public_id
      end
    else
      self.feat_img = "img_placeholder.png"
    end
    self.save
  end

  def set_description
    @journey = Journey.last
    @journey.description = params[:description]
    @journey.save
  end

  def show_time(created_at)
    created_at.strftime('%b %e %Y')
  end

  geocoded_by :location
  after_validation :geocode

end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController

  layout "photo_layout", only: [:gallery]

  before_action :set_journey, only: [:show, :edit, :update, :destroy, :gallery]
  before_action :require_login, only: [:edit, :new, :create, :update, :destroy]

  def index
      @user = User.find(params[:user_id])
      @journeys = @user.owend_journeys.order(:start_date)

      respond_to do |format|
        format.html {  render layout: "journey_layout"}
        format.json { render json: @journeys }
      end

  end

  def new
    @journey = Journey.new
    @user =  current_user
  end

  def show
    @diary_entries = @journey.diary_entries.order('date')
    @comment = Comment.new
    @user = @journey.owner
  end

  def gallery
    @user = @journey.owner
    @comment = Comment.new
  end

  def edit
  end

  def create
    if journey_params[:title] == Journey.last.title
      render nothing: true
    else
      if journey_params.has_key?("description")
        if journey_params[:description].size > 0
          @journey = current_user.owend_journeys.last
          @journey.update_attributes(journey_params)
          @journey.save
          render nothing: true, status: 200
        else
          render nothing: true
          flash[:alert] = "Description Cannot be Blank!"
        end
      else

        if current_user
          @user = current_user
          @journey = @user.owend_journeys.build(journey_params)

          if @journey.save
            @journey.set_feat_img
            redirect_to @journey, notice: "Journey successfully created!"
          else
            render :new
          end
        end
      end
    end

  end

  def destroy
    @journey.destroy
    redirect_to :user
  end

  def update
      if @journey.update_attributes(journey_params)
        redirect_to journey_path(@journey)
      else
        render :edit
      end
  end


  private

  def set_journey
    @journey = Journey.find(params[:id])
  end

  def journey_params
    params.require(:journey)
          .permit(:title, :description, :location, :start_date, :end_date, :feat_img, :imageable_id, :imageable_type, :name, :picture, :file, :latitude, :longitude)

  end
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/views/journeys/_form.html.erb
<%= form_for @journey do |f| %>
  <div class="field">
    <%= f.label :title  %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>



    <!-- <%= f.fields_for :photos  do |builder| %>
     <%= render "photos_fields", :f => builder %>
    <% end %> -->
  <!-- <div class="field">
    <%= f.label :feature_image %>
    <%= f.text_field :feat_img%>
  </div> -->

<% end %>

app/views/journeys/_jourey.html.erb
<li class="journey">
  <%= link_to journey.title, journey_path(journey) %>
</li>

app/views/journeys/_journey.html.erb
<li class="journey">
  <%= link_to journey.title, journey_path(journey) %>
</li>

app/views/journeys/_photos_fields.html.erb
  <%= f.label :name  %>
  <br>
  <%= f.text_field :name %>
  <br>
  <div class="dropzone-previews"></div>
  <br>

  <%= f.hidden_field :imageable_id, :value => @journey.id %>
  <%= f.hidden_field :imageable_type, :value => @journey.class %>

app/views/journeys/edit.html.erb
<div class="new-journey-wrapper">


<div class="logo">
  <%= link_to root_url do%>
  <%= image_tag ("logo-blue.png")  %>
  <% end %>
</div>

    <ul class="navigation">
      <li>
        <%= link_to current_user, :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-profile.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-profile-hover.png"%>
          <p>My Profile</p>
        </div>
      <% end %>
    </li>

      <li>
        <%= link_to user_journeys_path(current_user), :"data-no-turbolink" => true do %>
          <span>
          <%=  image_tag "MenuBar-icon-Journey.png"  %>
          </span>
          <div class="menu-out">
            <%= image_tag "MenuBar-icon-Journey-hover.png"%>
            <p>My Journey</p>
          </div>
        <% end %>
      </li>

      <li>
        <%= link_to user_photos_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-PhotoGallery.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-PhotoGallery-hover.png"%>
          <p>Gallery</p>
        </div>
        <% end %>
      </li>

      <li>
        <%= link_to new_journey_path, :"data-no-turbolink" => true do  %>
        <span>
        <%=  image_tag "MenuBar-icon-timeline.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-timeline-hover.png"%>
          <p>New Journey</p>
        </div>
        <% end %>
    </li>

      <li>
        <%= link_to user_favourites_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-favorites.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-favorites-hover.png"%>
          <p>Favourites</p>
        </div>
        <% end %>
    </li>
      <!-- <li><a href="#contact">
        <img src="./images/contact.png" />
      </a></li> -->
    </ul>
<!-- multistep form -->
<div id="msform">
	<!-- progressbar -->

	<ul id="progressbar">
		<li class="active">Basic Info</li>
		<li>About this Journey </li>
		<li>Photo Collection</li>
	</ul>
	<!-- fieldsets -->
	<fieldset>
		<h2 class="fs-title">Create your Journey</h2>
		<h3 class="fs-subtitle">This is step 1</h3>
	  <%= render 'form' %>
		<input type="button" name="next" class="next action-button" value="Next" id="first_submit" />
	</fieldset>
	<fieldset>
		<h2 class="fs-title">Desciption</h2>
		<h3 class="fs-subtitle">Descripe this journey</h3>
      <%= form_for @journey, html: { class:"editing-journey" } do |f| %>
      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
      <% end %>

		<!-- <input type="text" name="twitter" placeholder="Twitter" />
		<input type="text" name="facebook" placeholder="Facebook" />
		<input type="text" name="gplus" placeholder="Google Plus" /> -->

		<input type="button" name="previous" class="previous action-button" value="Previous" />
		<input type="button" id="second_submit" name="next" class="next action-button" value="Next" />
	</fieldset>
	<fieldset id="journey-last-step">
		<h2 class="fs-title">Photos</h2>
		<h3 class="fs-subtitle">
      <p>Upload your photos here</p>
      <p>(feature image can be set in the gallery)</p>
    </h3>
    <div class="photo-form" id="photo-last-step">
      <%= form_for Photo.new, html: { multipart: true, id: "my-awesome-dropzone", class: "dropzone"} do |t| %>

      <!-- <%= t.label :name  %>
      <br>
      <%= t.text_field :name %> -->

      <div class="dropzone-previews"></div>
      <br>
      <%= t.hidden_field :imageable_id, :value => @journey.id %>
     <%= t.hidden_field :imageable_type, :value => @journey.class %>
      <% end  %>
		<!-- <input type="text" name="fname" placeholder="First Name" />
		<input type="text" name="lname" placeholder="Last Name" />
		<input type="text" name="phone" placeholder="Phone" />
		<textarea name="address" placeholder="Address"></textarea> -->
    </div>
		<input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="submit" name="submit" class="submit action-button" value="Submit" id="final_submit" />
	</fieldset>
</div>

<div class="h-link">
  <%= link_to "",  journey_path(@journey), method: :get%>
</div>
</div>

app/views/journeys/gallery.html.erb
<style media="screen">
a:hover{
color:none;
background: transparent;
opacity: 1.0;
}

body {
  background-image: url("concrete_seamless.png");
  background-repeat:repeat;
}
</style>
<div class="gallery-wrapper">

<div class="photo-gallery-title">
  <h1><%= @journey.title %></h1>
  <h2><%= @journey.show_time(@journey.start_date) %> - <%= @journey.show_time(@journey.end_date) %> &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;<%= @journey.location %></h2>
</div>





  <div class="gallery-container">
    <% if current_user == @journey.owner %>
      <div class="modal">
        <label for="modal-1">
          <div class="modal-trigger">  <div class="add-new-photo">
              <%= cl_image_tag("add_new.png") %>
            </div></div>
        </label>
        <input class="modal-state" id="modal-1" type="checkbox" />
        <div class="modal-fade-screen">
          <div class="modal-inner">
            <div class="modal-close" for="modal-1"></div>
            <h1>Click to Add</h1>
            <div class="photo-form">
              <%= form_for Photo.new, html: { multipart: true, id: "my-awesome-dropzone", class: "dropzone"} do |t| %>


              <div class="dropzone-previews"></div>
              <br>
              <%= t.hidden_field :imageable_id, :value => @journey.id %>
               <%= t.hidden_field :imageable_type, :value => @journey.class %>
              <% end  %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% @journey.photo_gallery.each do |p| %>
  <a class="fancybox img_small" href="#inline<%= p.id %>" title="<%= p.name %>" data-fancybox-group="gallery"><%= cl_image_tag(p.picture.url, :width=>250, :height=>250, :crop=>:fill) %></a>


  <div class="img_large" id="inline<%= p.id %>">

    <%= cl_image_tag(p.picture.url, :width=> 300, :height => 300, :crop => :fit) %>

    <%= button_to "Set journey's feature image", journey_photo_path(p.find_journey_of_photo, p), method: :put%>


    <%= render partial: 'comments/list', locals: { commentable: p } %>

    <% if current_user %>
      <!-- <h4>Write a comment:</h4> -->
      <div id="gallery-comment-form">
      <%= form_for [p, @comment], :html => {:class => "comment-form"} do |f| %>
      <%= render partial: 'comments/form', locals: { f: f, commentable: p} %>
      <% end %>
      </div>
    <% else %>
      <p>Please <%= link_to "log in", login_path %> to add a comment.</p>

    <% end %>

</div>

<% end %>
</div>
</div>

app/views/journeys/index.js.erb
$('#journeys').html(' <%= j(render @journeys) %>')

app/views/journeys/new.html.erb
<style >


body {
height: 100%;
background: url('images/AddNew-bg.jpg');
}

</style>

<div class="new-journey-wrapper">
  <div class="logo">
    <%= link_to root_url do%>
    <%= image_tag ("logo-blue.png")  %>
    <% end %>
  </div>

    <ul class="navigation">
      <li>
        <%= link_to current_user, :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-profile.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-profile-hover.png"%>
          <p>My Profile</p>
        </div>
      <% end %>
    </li>

      <li>
        <%= link_to user_journeys_path(current_user), :"data-no-turbolink" => true do %>
          <span>
          <%=  image_tag "MenuBar-icon-Journey.png"  %>
          </span>
          <div class="menu-out">
            <%= image_tag "MenuBar-icon-Journey-hover.png"%>
            <p>My Journey</p>
          </div>
        <% end %>
      </li>

      <li>
        <%= link_to user_photos_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-PhotoGallery.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-PhotoGallery-hover.png"%>
          <p>Gallery</p>
        </div>
        <% end %>
      </li>

      <li>
        <%= link_to new_journey_path, :"data-no-turbolink" => true do  %>
        <span>
        <%=  image_tag "MenuBar-icon-timeline.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-timeline-hover.png"%>
          <p>New Journey</p>
        </div>
        <% end %>
    </li>

      <li>
        <%= link_to user_favourites_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-favorites.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-favorites-hover.png"%>
          <p>Favourites</p>
        </div>
        <% end %>
    </li>
      <!-- <li><a href="#contact">
        <img src="./images/contact.png" />
      </a></li> -->
    </ul>
<!-- multistep form -->
<div id="msform">
	<!-- progressbar -->

	<ul id="progressbar">
		<li class="active">Basic Info</li>
		<li>About this Journey </li>
		<li>Photo Collection</li>
	</ul>
	<!-- fieldsets -->
	<fieldset>
		<h2 class="fs-title">Create your Journey</h2>
		<h3 class="fs-subtitle">This is step 1</h3>
	  <%= render 'form' %>
		<input type="button" name="next" class="next action-button" value="Next" id="first_submit" />
	</fieldset>
	<fieldset>
		<h2 class="fs-title">Desciption</h2>
		<h3 class="fs-subtitle">Descripe this journey</h3>
      <%= form_for @journey, url: '/journeys', html: { class:"existing-journey" } do |f| %>
      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
      <% end %>

		<!-- <input type="text" name="twitter" placeholder="Twitter" />
		<input type="text" name="facebook" placeholder="Facebook" />
		<input type="text" name="gplus" placeholder="Google Plus" /> -->

		<input type="button" name="previous" class="previous action-button" value="Previous" />
		<input type="button" id="second_submit" name="next" class="next action-button" value="Next" />
	</fieldset>
	<fieldset id="journey-last-step">
		<h2 class="fs-title">Photos</h2>
		<h3 class="fs-subtitle">
      <p>Upload your photos here</p>
      <p>(feature image can be set in the gallery)</p>
    </h3>
    <div class="photo-form" id="photo-last-step">
      <%= form_for Photo.new, html: { multipart: true, id: "my-awesome-dropzone", class: "dropzone"} do |t| %>

      <!-- <%= t.label :name  %>
      <br>
      <%= t.text_field :name %> -->

      <div class="dropzone-previews"></div>
      <br>
      <%= t.hidden_field :imageable_id, :value => @journey.id %>
     <%= t.hidden_field :imageable_type, :value => @journey.class %>
      <% end  %>
		<!-- <input type="text" name="fname" placeholder="First Name" />
		<input type="text" name="lname" placeholder="Last Name" />
		<input type="text" name="phone" placeholder="Phone" />
		<textarea name="address" placeholder="Address"></textarea> -->
    </div>
		<input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="submit" name="submit" class="submit action-button" value="Submit" id="final_submit" />
	</fieldset>
</div>

<div class="h-link">
  <%= link_to "", user_journeys_path(@user)%>
</div>
</div>

<script>
  $(document).ready(function () {

  $(".new_journey").validate({
  debug: true,
  rules: {
  "journey[title]": {required: true, minlength: 4},
  "journey[location]": {required: true, minlength: 6},
  "journey[start_date]": {required: true},
  "journey[end_date]": {required: true}
  // “user[password_confirmation]“: {required: true, equalTo: “#user_password”}
  }
  });


  $(".existing-journey").validate({
  debug: true,
  rules: {
  "journey[description]": {required: true, minlength: 7}

  // “user[password_confirmation]“: {required: true, equalTo: “#user_password”}
  }
  });

  });
</script>

app/views/journeys/show.html.erb
<!DOCTYPE html>

<body>

    <div class="back-img-journey">
      <div class="logo">
        <%= link_to root_url do%>
        <%= image_tag ("logo-blue.png")  %>
        <% end %>
      </div>
      <div class="journey-header-inner">
        <div class="journey-header-copy">
          <h1 class="journey-title"><%= @journey.title %></h1>
            <p class="journey-content"><%= @journey.description %></p>
        </div>

        <div class="journey-location-date">
          <div class="first-book">
              <div class="journey-location-icon-sm">
                <%= image_tag ("Entries_icon_location.png" )%> <strong>Location</strong>
              </div>
              <div class="journey-location-sm">
                  <strong><%= @journey.location %></strong>
              </div>
          </div>
          <div class="second-book">
            <div class="journey-location-icon-sm data-icon-book">
              <%= image_tag ("Entries_icon_time.png" )%> <strong>Start Date</strong>
            </div>
            <div class="journey-location-sm data-on-book">
                <strong><%= @journey.show_time(@journey.start_date) %></strong>
            </div>

          </div>
          <div class="third-book">
            <div class="journey-location-icon-sm data-icon-book">
              <%= image_tag ("Entries_icon_time.png" )%> <strong>End Date</strong>
            </div>
            <div class="journey-location-sm data-on-book">
                <strong><%=  @journey.show_time(@journey.end_date) %></strong>
            </div>

          </div>
        </div>
        <div class="journey-stat">
          <%= image_tag ('Entries_icon_tag.png') %>
          <h3 class="journey-stat-name">TAGS</h3>
          <div class="activity-tags">
             <% @journey.tags.each do |tag| %>
                <% if tag.body != "recommended" %>
                <div class="listing-tag">
                    <%= tag.body %>
                </div>
                  <% end %>
            <% end %>

            <% if current_user == @journey.owner %>
              <span class="add-new-tag"><%= link_to "Add Tags" %></span>



              <div class="tag-form">
                <%= form_for [@journey, Tag.new] do |t| %>

                <%= t.text_field :body%>
                <%= t.hidden_field :taggable_id, :value => @journey.id %>
                <%= t.hidden_field :taggable_type, :value => @journey.class %>
                <%= t.hidden_field :user_id, :value => current_user.id %>
                <%= t.submit "Add" %>
                <% end  %>
              </div>
            <% end %>
          </div>
      </div>
        <% if current_user && current_user != @journey.owner%>
        <div class="recommend">
          <% if @journey.tags.where(user_id: current_user.id, body: "recommended").size > 0 %>
            <button class="recommend-alreday" type="button" name="button">Recommend</button>
          <% else %>
            <div class="recommend-form">
              <%= form_for [@journey, Tag.new] do |t| %>
              <%= t.hidden_field :body, :value=> 'recommended' %>
              <%= t.hidden_field :taggable_id, :value => @journey.id %>
              <%= t.hidden_field :taggable_type, :value => @journey.class %>
              <%= t.hidden_field :user_id, :value => current_user.id %>
              <%= t.submit "Recommend" %>
              <% end  %>
            </div>
          <% end %>
        </div>
        <% if @journey.favourites.where(user_id: current_user.id).length > 0 %>
          <button class="f-already">
            <span class="fa fa-heart">
              </span>
          </button>
          <div class="favourite-form-already">
            <%= form_for [@journey, @journey.favourites.where(user_id: current_user.id)[0]], method: :delete do |f| %>
            <%= f.button :class => "submit-already" %>
            <% end %>
          </div>
        <% else %>
          <button class="no-f-yet">
            <span class="fa fa-heart">
              </span>
          </button>
          <div class="favourite-form">
            <%= form_for [@journey, Favourite.new] do |f| %>
            <%= f.button :class => "f-submit" %>
          </div>
            <% end %>
        <% end %>
      <% end %>

  </div>
</div>


  <% if current_user %>
    <ul class="navigation">
      <li>
        <%= link_to current_user, :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-profile.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-profile-hover.png"%>
          <p>My Profile</p>
        </div>
      <% end %>
    </li>

      <li>
        <%= link_to user_journeys_path(current_user), :"data-no-turbolink" => true do %>
          <span>
          <%=  image_tag "MenuBar-icon-Journey.png"  %>
          </span>
          <div class="menu-out">
            <%= image_tag "MenuBar-icon-Journey-hover.png"%>
            <p>My Journey</p>
          </div>
        <% end %>
      </li>

      <li>
        <%= link_to user_photos_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-PhotoGallery.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-PhotoGallery-hover.png"%>
          <p>Gallery</p>
        </div>
        <% end %>
      </li>
      <li>
        <%= link_to new_journey_path, :"data-no-turbolink" => true do  %>
        <span>
        <%=  image_tag "MenuBar-icon-timeline.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-timeline-hover.png"%>
          <p>New Journey</p>
        </div>
        <% end %>
    </li>

      <li>
        <%= link_to user_favourites_path(current_user), :"data-no-turbolink" => true do %>
        <span>
        <%=  image_tag "MenuBar-icon-favorites.png"  %>
        </span>
        <div class="menu-out">
          <%= image_tag "MenuBar-icon-favorites-hover.png"%>
          <p>Favourites</p>
        </div>
        <% end %>
    </li>
      <!-- <li><a href="#contact">
        <img src="./images/contact.png" />
      </a></li> -->
    </ul>
  <% end %>



<div class="journey-wrapper">
  <div class="journey-buttons-section">
    <% if current_user == @journey.owner %>
    <%= link_to "EDIT JOURNEY", edit_journey_path(@journey), :"data-no-turbolink" => true, :"class" => "profile-button" %>
      <div class = "button-border" >EDIT JOURNEY</div>
    <% end %>

      <%= link_to "PHOTO GALLERY", gallery_journey_path(@journey), :"data-no-turbolink" => true,  :"class" => "profile-button" %>
      <div class = "button-border" >PHOTO GALLERY</div>
  </div>

  <div class="journey-diaries-section">
    <% if current_user == @journey.owner %>
    <div class="new_diary_entry_block diary_entry_block">
      <%= link_to new_journey_diary_entry_path(@journey), :"data-no-turbolink" => true do %>
        <%= cl_image_tag("add_new.png") %>
      <% end %>
    </div>
    <% end %>
    <% if @journey.diary_entries.any? %>
      <%= render @diary_entries %>
    <% end %>



  </div>

  <% if @journey.diary_entries.size > 0 %>
    <div id="journey_path_map" data-diaries="<%=@journey.diary_entries.to_json%>"></div>
  <% else %>
    <div id="journey_path_map" data-diaries="<%=@journey.to_json%>"></div>
  <% end %>

  <div class="comment-form-list-section">
    <div class="comment-form journey_aside">
      <%= image_tag ("Entries_SectionTitle_Comments.png") %>
      <% if current_user %>

        <%= form_for [@journey, @comment], :html => {:class => "comment-form"} do |f| %>
        <%= render partial: 'comments/form', locals: { f: f, commentable: @journey} %>
        <% end %>
      <% else %>
        <p>Please <%= link_to "log in", login_path %> to add a comment.</p>
      <% end %>

    </div>
    <div class="comment-list journey_article">
      <%= render partial: 'comments/list', locals: { commentable: @journey }  %>

  </div>

</div>

</body>