config/routes.rb
Rails.application.routes.draw do

  root 'users#home'

  resources :photos, only: [:create, :show] do
    resources :comments, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]

  end

  resources :journeys, except: [:index] do
    resources :diary_entries do
      resources :favourites, only: [:create, :destroy]
      resources :tags, only: [:create, :destroy, :show]
      resources :comments, only: [:create, :destroy]
    end
    resources :favourites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy, :show]
    resources :comments, only: [:create, :destroy]
    member do
      get :gallery
    end
    resources :photos, only: [:show, :update]
  end

  resources :tags, only: [:index]

  resources :users do
    member do
      get :followings, :followers
    end
    resources :photos
    resources :journeys, only: [:index]
    resources :favourites, only: [:index]
  end

  resources :relationships, only: [:destroy, :create]
  resources :password_resets

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  layout false
  def new
     @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_to(root_url, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      redirect_to :login
    end
  end

  def destroy
    logout
    redirect_to( root_url, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
    <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
    <%= text_field_tag :email, nil, :placeholder => "Enter Your Email", class:"login-input"  %>
    <%= password_field_tag :password, nil, :placeholder => "Password", class:"login-input" %>
    <%= submit_tag "Login", :"data-no-turbolink" => true, class: "btn_login", onclick: "cambiar_login()"%>

  <%= label_tag :emember, "Remember me", class:"remeber-me" %> <%= check_box_tag :remember, params[:remember], true %>

<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<!-- <h1>UserSessions#new</h1>
<p>Find me in app/views/user_sessions/new.html.erb</p> -->

<%= stylesheet_link_tag    "//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css"%>
<%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Caveat:400,700"  %>
<%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['google_maps_api_key']}" %>


<%= csrf_meta_tags %>

<style media="screen">

* {
margin: 0px auto;
padding: 0px;
text-align: center;
font-family: 'Open Sans', sans-serif;
}

</style>
<div class="login-logo">
  <%= link_to root_url, :"data-no-turbolink" => true do%>
  <%= image_tag ("logo-blue.png")  %>
  <% end %>
</div>

<div class="login-wrapper">
<div class="cotn_principal">
<div class="cont_centrar">

  <div class="cont_login">
    <div class="cont_info_log_sign_up">
      <div class="col_md_login">
      <h2>LOGIN</h2>
        <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> -->
        <button class="btn_login" onclick="cambiar_login()">LOGIN</button>
        </div>
      <div class="col_md_sign_up">
        <h2>SIGN UP</h2>
      <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> -->
      <button class="btn_sign_up" onclick="cambiar_sign_up()">SIGN UP</button>
        </div>
       </div>


    <div class="cont_back_info">
       <div class="cont_img_back_grey">
       </div>

    </div>
    <div class="cont_forms" >
        <div class="cont_img_back_">
         </div>
     <div class="cont_form_login">
        <a href="#" onclick="ocultar_login_sign_up()" ><%= image_tag("icon-back.png", size: "30x30") %></a>
           <h2>LOGIN</h2>
            <%= render 'form' %>
      </div>

   <div class="cont_form_sign_up">
    <a href="#" onclick="ocultar_login_sign_up()"><%= image_tag("icon-back.png", size: "30x30") %></a>
         <h2>SIGN UP</h2>
         <%= render partial: 'users/form' %>
    <!-- <input type="text" placeholder="Email" />
    <input type="text" placeholder="User" />
    <input type="password" placeholder="Password" />
    <input type="password" placeholder="Confirm Password" />
    <button class="btn_sign_up" onclick="cambiar_sign_up()">SIGN UP</button> -->

  </div>

    </div>

  </div>
 </div>
</div>
</div>














<!-- <h1>Login</h1>

<%= render 'form' %>


<h1>Forgot Password?</h1>

<%= render 'forgot_password_form' %>

<%= link_to 'Back', :journeys %> -->